PREFIX :      <file:///C:/Users/chiarcos/Desktop/corpus/revised-srl/ewt-conll/#>
PREFIX powla: <http://purl.org/powla/powla.owl#>
PREFIX conll: <http://ufal.mff.cuni.cz/conll2009-st/task-description.html#>
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX terms: <http://purl.org/acoli/open-ie/>
PREFIX x:     <http://purl.org/acoli/conll-rdf/xml#>
PREFIX nif:   <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX srl:   <http://purl.org/acoli/open-ie/srl/>
PREFIX tmp:   <http://purl.org/acoli/open-ie/tmp/>

# extrapolate UPOS annotations from PTB annotations
# bootstrapped from EWT, extended for IBM corpora
INSERT {
	?w conll:UPOS ?upos
} WHERE {
	?w conll:XPOS ?xpos.
	MINUS { ?w conll:UPOS [] }
	VALUES ( ?xpos ?upos) {
		("-LRB-" 	"PUNCT")
		("-RRB-" 	"PUNCT")
		("," 	"PUNCT")
		(":" 	"PUNCT")
		("." 	"PUNCT")
		("''" 	"PUNCT")
		('"' 	"PUNCT")
		("(" 	"PUNCT")
		(")" 	"PUNCT")
		("``" 	"PUNCT")
		("$" 	"SYM")
		("ADD" 	"X")
		("AFX" 	"X")
		("CC" 	"CONJ")
		("CD" 	"NUM")
		("DT" 	"DET")
		("EX" 	"PRON")
		("FW" 	"X")
		("GW" 	"X")
		("HYPH" 	"PUNCT")
		("IN" 	"ADP")
		("JJ" 	"ADJ")
		("JJR" 	"ADJ")
		("JJS" 	"ADJ")
		("LS" 	"X")
		("MD" 	"AUX")
		("NFP" 	"PUNCT")
		("NN" 	"NOUN")
		("NNP" 	"PROPN")
		("NNPS" 	"PROPN")
		("NNS" 	"NOUN")
		("PDT" 	"DET")
		("POS" 	"PART")
		("PRP" 	"PRON")
		("PRP$" 	"PRON")
		("QT" 	"NUM")
		("RB" 	"ADV")
		("RBR" 	"ADV")
		("RBS" 	"ADV")
		("RP" 	"ADP")
		("SYM" 	"SYM")
		("TO" 	"PART")
		("UH" 	"INTJ")
		("UNKNOWN" 	"X")
		("VB" 	"VERB")
		("VBD" 	"VERB")
		("VBG" 	"VERB")
		("VBN" 	"VERB")
		("VBP" 	"VERB")
		("VBZ" 	"VERB")
		("WDT" 	"PRON")
		("WP" 	"PRON")
		("WP$" 	"PRON")
		("WRB" 	"ADV")
		("XX" 	"X")
	}
}
